import random
from HumanNames import HumanNames


class NPCNames:

    def __init__(self, race, gender, age, skin_color):
        if race in ["dragonborn"]:
            if gender in ["female"]:
                self.first_names = ["Akra", "Aasathra", "Antrara",
                                    "Arava", "Biri", "Blendaeth",
                                    "Burana", "Chassath", "Daar",
                                    "Dentratha", "Doudra", "Driindar",
                                    "Eggren", "Farideh", "Findex",
                                    "Furrele", "Gesrethe", "Gilkass",
                                    "Harann", "Havilar", "Hethress",
                                    "Hillanot", "Jaxi", "Jezean",
                                    "Jheri", "Kadana", "Kava",
                                    "Korinn", "Megren", "Mijira",
                                    "Mishann", "Nala", "Nuthra",
                                    "Perra", "Pogranix", "Pyxrin",
                                    "Quespa", "Raiann", "Rezena",
                                    "Ruloth", "Saphara", "Savaran",
                                    "Sora", "Surina", "Synthrin",
                                    "Tatyan", "Thava", "Uadjit",
                                    "Vezera", "Zykroff"]
            elif gender in ["male"]:
                self.first_names = ["Adrex", "Arjhan", "Azzakh",
                                    "Balasar", "Baradad", "Bharash",
                                    "Bidreked", "Dadalan", "Dazzazn",
                                    "Direcris", "Donaar", "Fax",
                                    "Gargax", "Ghesh", "Gorbundus",
                                    "Greethen", "Heskan", "Hirrathak",
                                    "Ildrex", "Kaladan", "Kerkad",
                                    "Kiirith", "Kriv", "Maagog",
                                    "Medrash", "Mehen", "Mozikth",
                                    "Mreksh", "Mugrunden", "Nadarr",
                                    "Nithther", "Norkuuth", "Nykkan",
                                    "Pandjed", "Patrin", "Pijjirik",
                                    "Quarethon", "Rathkran", "Rhogar",
                                    "Rivaan", "Sethrekar", "Shamash",
                                    "Shedinn", "Srorthen", "Tarhun",
                                    "Torinn" "Trynnicus", "Valorean",
                                    "Vrondiss", "Zedaar"]
            else:
                self.first_names = ["Akra", "Aasathra", "Antrara",
                                    "Arava", "Biri", "Blendaeth",
                                    "Burana", "Chassath", "Daar",
                                    "Dentratha", "Doudra", "Driindar",
                                    "Eggren", "Farideh", "Findex",
                                    "Furrele", "Gesrethe", "Gilkass",
                                    "Harann", "Havilar", "Hethress",
                                    "Hillanot", "Jaxi", "Jezean",
                                    "Jheri", "Kadana", "Kava",
                                    "Korinn", "Megren", "Mijira",
                                    "Mishann", "Nala", "Nuthra",
                                    "Perra", "Pogranix", "Pyxrin",
                                    "Quespa", "Raiann", "Rezena",
                                    "Ruloth", "Saphara", "Savaran",
                                    "Sora", "Surina", "Synthrin",
                                    "Tatyan", "Thava", "Uadjit",
                                    "Vezera", "Zykroff", "Adrex",
                                    "Arjhan", "Azzakh", "Balasar",
                                    "Baradad", "Bharash", "Bidreked",
                                    "Dadalan", "Dazzazn", "Direcris",
                                    "Donaar", "Fax", "Gargax",
                                    "Ghesh", "Gorbundus", "Greethen",
                                    "Heskan", "Hirrathak", "Ildrex",
                                    "Kaladan", "Kerkad", "Kiirith",
                                    "Kriv", "Maagog", "Medrash",
                                    "Mehen", "Mozikth", "Mreksh",
                                    "Mugrunden", "Nadarr", "Nithther",
                                    "Norkuuth", "Nykkan", "Pandjed",
                                    "Patrin", "Pijjirik", "Quarethon",
                                    "Rathkran", "Rhogar", "Rivaan",
                                    "Sethrekar", "Shamash", "Shedinn",
                                    "Srorthen", "Tarhun", "Torinn",
                                    "Trynnicus", "Valorean", "Vrondiss", "Zedaar"]
        elif race in ["hill dwarf", "mountain dwarf", "duergar dwarf"]:
            if gender in ["female"]:
                self.first_names = ["Anbera", "Artin", "Audhild",
                                    "Balifra", "Barbena", "Bardryn",
                                    "Bolhild", "Dagnal", "Dariff",
                                    "Delre", "Diesa," "Eldeth,"
                                             "Eridred", "Falkrunn", "Fallthra",
                                    "Finellen", "Gillydd", "Gunnloda",
                                    "Gurdis", "Helgret", "Helja",
                                    "Hlin", "Ilde", "Jarana",
                                    "Kathra", "Kilia", "Kristryd",
                                    "Liftrasa", "Marastyr", "Mardred",
                                    "Morana", "Nalaed", "Nora",
                                    "Nurkara", "Oriff", "Ovina",
                                    "Riswynn", "Sannl", "Therlin",
                                    "Thodris", "Torbera", "Tordrid",
                                    "Torgga", "Urshar", "Valida",
                                    "Vistra", "Vonana", "Werydd",
                                    "Whurdred", "Yurgunn"]
            elif gender in ["male"]:
                self.first_names = ["Adrik" "Alberich" "Baern",
                                    "Barendd", "Beloril", "Brottor",
                                    "Dain", "Dalgal", "Darrak",
                                    "Delg", "Duergath", "Dworic",
                                    "Eberk", "Einkil", "Elaim",
                                    "Erias", "Fallond", "Fargrim",
                                    "Gardain", "Gilthur", "Gimgen",
                                    "Gimurt", "Harbek", "Kildrak",
                                    "Kilvar", "Morgran", "Morkral",
                                    "Nalral", "Nordak", "Nuraval",
                                    "Oloric", "Olunt", "Orsik",
                                    "Oskar", "Rangrim", "Reirak",
                                    "Rurik", "Taklinn", "Thoradin",
                                    "Thorin", "Thradal", "Tordek",
                                    "Traubon", "Travok", "Ulfgar",
                                    "Uraim", "Veit", "Vonbin",
                                    "Vondal", "Whurbin"]
            else:
                self.first_name = ["Anbera", "Artin", "Audhild",
                                   "Balifra", "Barbena", "Bardryn",
                                   "Bolhild", "Dagnal", "Dariff",
                                   "Delre", "Diesa," "Eldeth,"
                                            "Eridred", "Falkrunn", "Fallthra",
                                   "Finellen", "Gillydd", "Gunnloda",
                                   "Gurdis", "Helgret", "Helja",
                                   "Hlin", "Ilde", "Jarana",
                                   "Kathra", "Kilia", "Kristryd",
                                   "Liftrasa", "Marastyr", "Mardred",
                                   "Morana", "Nalaed", "Nora",
                                   "Nurkara", "Oriff", "Ovina",
                                   "Riswynn", "Sannl", "Therlin",
                                   "Thodris", "Torbera", "Tordrid",
                                   "Torgga", "Urshar", "Valida",
                                   "Vistra", "Vonana", "Werydd",
                                   "Whurdred", "Yurgunn", "Adrik"
                                                          "Alberich" "Baern", "Barendd",
                                   "Beloril", "Brottor", "Dain",
                                   "Dalgal", "Darrak", "Delg",
                                   "Duergath", "Dworic", "Eberk",
                                   "Einkil", "Elaim", "Erias",
                                   "Fallond", "Fargrim", "Gardain",
                                   "Gilthur", "Gimgen", "Gimurt",
                                   "Harbek", "Kildrak", "Kilvar",
                                   "Morgran", "Morkral", "Nalral",
                                   "Nordak", "Nuraval", "Oloric",
                                   "Olunt", "Orsik", "Oskar",
                                   "Rangrim", "Reirak", "Rurik",
                                   "Taklinn", "Thoradin", "Thorin",
                                   "Thradal", "Tordek", "Traubon",
                                   "Travok", "Ulfgar", "Uraim",
                                   "Veit", "Vonbin", "Vondal", "Whurbin"]
        elif race in ["high elf", "wood elf", "eladrin elf", "drow", "firbolg"]:
            if age < 18:
                self.first_names = ["Ael", "Ang", "Ara",
                                    "Ari", "Arn", "Aym",
                                    "Broe", "Bryn", "Cael",
                                    "Cy", "Dae", "Del",
                                    "Eli", "Eryn", "Faen",
                                    "Fera", "Gael", "Gar",
                                    "Innil", "Jar", "Kan",
                                    "Koeth", "Lael", "Lue",
                                    "Mai", "Mara", "Mella",
                                    "Mya", "Naeris", "Naill",
                                    "Nim", "Phann", "Py",
                                    "Rael", "Raer", "Ren",
                                    "Rinn", "Rua", "Sael",
                                    "Sai", "Sumi", "Syllin",
                                    "Ta", "Thia", "Tia",
                                    "Traki", "Vall", "Von",
                                    "Wil", "Za"]
            elif gender in ["female"]:
                self.first_names = ["Adrie", "Ahinar", "Althaea",
                                    "Anastrianna", "Andraste", "Antinua",
                                    "Arara", "Baelitae", "Bethrynna",
                                    "Birel", "Caelynn", "Chaedi",
                                    "Claira", "Dara", "Drusilia",
                                    "Elama", "Enna", "Faral",
                                    "Felosial", "Hatae", "Ielenia",
                                    "Ilanis", "Irann", "Jarsali",
                                    "Jelenneth", "Keyleth", "Leshanna",
                                    "Lia", "Maiathah", "Malquis",
                                    "Meriele", "Mialee", "Myathethil",
                                    "Naivara", "Quelenna", "Quillathe",
                                    "Ridaro", "Sariel", "Shanairla",
                                    "Shava", "Silaqui", "Sumnes",
                                    "Theirastra", "Thiala", "Tiaathque",
                                    "Traulam", "Vadania", "Valanthe",
                                    "Valna", "Xanaphia"]
            elif gender in ["male"]:
                self.first_names = ["Adran", "Aelar", "Aerdeth",
                                    "Ahvain", "Aramil", "Arannis",
                                    "Aust", "Azaki", "Beiro",
                                    "Berrian", "Caeldrim", "Carric",
                                    "Dayereth", "Dreali", "Efferil",
                                    "Eiravel", "Enialis", "Erdan",
                                    "Erevan", "Fivin", "Galinndan",
                                    "Gennal", "Hadarai", "Halimath",
                                    "Heian", "Himo", "Immeral",
                                    "Ivellios", "Korfel", "Lamlis",
                                    "Laucian", "Lucan", "Mindartis",
                                    "Naal", "Nutae", "Paelias",
                                    "Peren", "Quarion", "Riardon",
                                    "Rolen", "Soveliss", "Suhnae",
                                    "Thamior", "Tharivol", "Theren",
                                    "Theriatis", "Thervan", "Uthemar",
                                    "Vanuath", "Varis"]
            else:
                self.first_names = ["Adrie", "Ahinar", "Althaea",
                                    "Anastrianna", "Andraste", "Antinua",
                                    "Arara", "Baelitae", "Bethrynna",
                                    "Birel", "Caelynn", "Chaedi",
                                    "Claira", "Dara", "Drusilia",
                                    "Elama", "Enna", "Faral",
                                    "Felosial", "Hatae", "Ielenia",
                                    "Ilanis", "Irann", "Jarsali",
                                    "Jelenneth", "Keyleth", "Leshanna",
                                    "Lia", "Maiathah", "Malquis",
                                    "Meriele", "Mialee", "Myathethil",
                                    "Naivara", "Quelenna", "Quillathe",
                                    "Ridaro", "Sariel", "Shanairla",
                                    "Shava", "Silaqui", "Sumnes",
                                    "Theirastra", "Thiala", "Tiaathque",
                                    "Traulam", "Vadania", "Valanthe",
                                    "Valna", "Xanaphia", "Adran",
                                    "Aelar", "Aerdeth", "Ahvain",
                                    "Aramil", "Arannis", "Aust",
                                    "Azaki", "Beiro", "Berrian",
                                    "Caeldrim", "Carric", "Dayereth",
                                    "Dreali", "Efferil", "Eiravel",
                                    "Enialis", "Erdan", "Erevan",
                                    "Fivin", "Galinndan", "Gennal",
                                    "Hadarai", "Halimath", "Heian",
                                    "Himo", "Immeral", "Ivellios",
                                    "Korfel", "Lamlis", "Laucian",
                                    "Lucan", "Mindartis", "Naal",
                                    "Nutae", "Paelias", "Peren",
                                    "Quarion", "Riardon", "Rolen",
                                    "Soveliss", "Suhnae", "Thamior",
                                    "Tharivol", "Theren", "Theriatis",
                                    "Thervan", "Uthemar", "Vanuath", "Varis"]
        elif race in ["forest gnome", "rock gnome", "deep gnome"]:
            if gender in ["female"]:
                self.first_names = ["Abalaba", "Bimpnottin", "Breena",
                                    "Buvvie", "Callybon", "Caramip",
                                    "Carlin", "Cumpen", "Dalaba",
                                    "Donella", "Duvamil", "Ella",
                                    "Ellyjoybell", "Ellywick", "Enidda",
                                    "Lilli", "Loopmottin", "Lorilla",
                                    "Luthra", "Mardnab", "Meena",
                                    "Menny", "Mumpena", "Nissa",
                                    "Numba", "Nyx", "Oda",
                                    "Oppah", "Orla", "Panana",
                                    "Pyntle", "Quilla", "Ranala",
                                    "Reddlepop", "Roywyn", "Salanop",
                                    "Shamil", "Siffress", "Symma",
                                    "Tana", "Tenena", "Tervaround",
                                    "Tippletoe", "Ulla", "Unvera",
                                    "Veloptima", "Virra", "Waywocket",
                                    "Yebe", "Zanna"]
            elif gender in ["male"]:
                self.first_names = ["Alston", "Alvyn", "Anverth",
                                    "Arumawann", "Bilbron", "Boddynock",
                                    "Brocc", "Burgell", "Cockaby",
                                    "Crampernap", "Dabbledob", "Delebean",
                                    "Dimble", "Eberdeb", "Eldon",
                                    "Erky", "Fablen", "Fibblestib",
                                    "Fonkin", "Frouse", "Frug",
                                    "Gerbo", "Gimble", "Glim",
                                    "Igden", "Jabble", "Jebeddo",
                                    "Kellen", "Kipper", "Namfoodle",
                                    "Oppleby", "Orryn", "Paggen",
                                    "Pallabar", "Pog", "Qualen",
                                    "Ribbles", "Rimple", "Roondar",
                                    "Sapply", "Seebo", "Senteq",
                                    "Sindri", "Umpen", "Warryn",
                                    "Wiggens", "Wobbles", "Wrenn",
                                    "Zaffrab", "Zook"]
            else:
                self.first_names = ["Abalaba", "Bimpnottin", "Breena",
                                    "Buvvie", "Callybon", "Caramip",
                                    "Carlin", "Cumpen", "Dalaba",
                                    "Donella", "Duvamil", "Ella",
                                    "Ellyjoybell", "Ellywick", "Enidda",
                                    "Lilli", "Loopmottin", "Lorilla",
                                    "Luthra", "Mardnab", "Meena",
                                    "Menny", "Mumpena", "Nissa",
                                    "Numba", "Nyx", "Oda",
                                    "Oppah", "Orla", "Panana",
                                    "Pyntle", "Quilla", "Ranala",
                                    "Reddlepop", "Roywyn", "Salanop",
                                    "Shamil", "Siffress", "Symma",
                                    "Tana", "Tenena", "Tervaround",
                                    "Tippletoe", "Ulla", "Unvera",
                                    "Veloptima", "Virra", "Waywocket",
                                    "Yebe", "Zanna", "Alston",
                                    "Alvyn", "Anverth", "Arumawann",
                                    "Bilbron", "Boddynock", "Brocc",
                                    "Burgell", "Cockaby", "Crampernap",
                                    "Dabbledob", "Delebean", "Dimble",
                                    "Eberdeb", "Eldon", "Erky",
                                    "Fablen", "Fibblestib", "Fonkin",
                                    "Frouse", "Frug", "Gerbo",
                                    "Gimble", "Glim", "Igden",
                                    "Jabble", "Jebeddo", "Kellen",
                                    "Kipper", "Namfoodle", "Oppleby",
                                    "Orryn", "Paggen", "Pallabar",
                                    "Pog", "Qualen", "Ribbles",
                                    "Rimple", "Roondar", "Sapply",
                                    "Seebo", "Senteq", "Sindri",
                                    "Umpen", "Warryn", "Wiggens",
                                    "Wobbles", "Wrenn", "Zaffrab", "Zook"]
        elif race in ["lightfoot halfling", "stout halfling"]:
            if gender in ["female"]:
                self.first_names = ["Alain", "Andry", "Anne",
                                    "Bella", "Blossom", "Bree",
                                    "Callie", "Chenna", "Cora",
                                    "Dee", "Dell", "Eida",
                                    "Eran", "Euphemia", "Georgina",
                                    "Gynnie", "Harriet", "Jasmine",
                                    "Jillian", "Jo", "Kithri",
                                    "Lavinia", "Lidda", "Maegan",
                                    "Marigold", "Merla", "Myria",
                                    "Nedda", "Nikki", "Nora",
                                    "Olivia", "Paela", "Pearl",
                                    "Pennie", "Philomena", "Portia",
                                    "Robbie", "Rose", "Saral",
                                    "Seraphina", "Shaena", "Stacee",
                                    "Tawna", "Thea", "Trym",
                                    "Tyna", "Vani", "Verna",
                                    "Wella", "Willow"]
            elif gender in ["male"]:
                self.first_names = ["Alton", "Ander", "Bernie",
                                    "Bobbin", "Cade", "Callus",
                                    "Corrin", "Dannad", "Danniel",
                                    "Eddie", "Egart", "Eldon",
                                    "Errich", "Fildo", "Finnan",
                                    "Franklin", "Garret", "Garth",
                                    "Gilbert", "Gob", "Harol",
                                    "Igor", "Jasper", "Keith",
                                    "Kevin", "Lazam", "Lerry",
                                    "Lindal", "Lyle", "Merric",
                                    "Mican", "Milo", "Morrin",
                                    "Nebin", "Nevil", "Osborn",
                                    "Ostran", "Oswalt", "Perrin",
                                    "Poppy", "Reed", "Roscoe",
                                    "Sam", "Shardon", "Tye",
                                    "Ulmo", "Wellby", "Wendel",
                                    "Wenner", "Wes"]
            else:
                self.first_names = ["Alain", "Andry", "Anne",
                                    "Bella", "Blossom", "Bree",
                                    "Callie", "Chenna", "Cora",
                                    "Dee", "Dell", "Eida",
                                    "Eran", "Euphemia", "Georgina",
                                    "Gynnie", "Harriet", "Jasmine",
                                    "Jillian", "Jo", "Kithri", "Lavinia",
                                    "Lidda", "Maegan", "Marigold",
                                    "Merla", "Myria", "Nedda",
                                    "Nikki", "Nora", "Olivia",
                                    "Paela", "Pearl", "Pennie",
                                    "Philomena", "Portia", "Robbie",
                                    "Rose", "Saral", "Seraphina",
                                    "Shaena", "Stacee", "Tawna",
                                    "Thea", "Trym", "Tyna",
                                    "Vani", "Verna", "Wella",
                                    "Willow", "Alton", "Ander",
                                    "Bernie", "Bobbin", "Cade",
                                    "Callus", "Corrin", "Dannad",
                                    "Danniel", "Eddie", "Egart",
                                    "Eldon", "Errich", "Fildo",
                                    "Finnan", "Franklin", "Garret",
                                    "Garth", "Gilbert", "Gob",
                                    "Harol", "Igor", "Jasper",
                                    "Keith", "Kevin", "Lazam",
                                    "Lerry", "Lindal", "Lyle",
                                    "Merric", "Mican", "Milo",
                                    "Morrin", "Nebin", "Nevil",
                                    "Osborn", "Ostran", "Oswalt",
                                    "Perrin", "Poppy", "Reed",
                                    "Roscoe", "Sam", "Shardon",
                                    "Tye", "Ulmo", "Wellby",
                                    "Wendel", "Wenner", "Wes"]
        elif race in ["half orc", "orc"]:
            if gender in ["female"]:
                self.first_names = ["Arha", "Baggi", "Bendoo",
                                    "Bilga", "Brakka", "Creega",
                                    "Drenna", "Ekk", "Emen",
                                    "Engong", "Fistula", "Gaaki",
                                    "Gorga", "Grai", "Greeba",
                                    "Grigi", "Gynk", "Hrathy",
                                    "Huru", "Ilga", "Kabbarg",
                                    "Kansif", "Lagazi", "Lezre",
                                    "Murgen", "Murook", "Myev",
                                    "Nagrette", "Neega", "Nella",
                                    "Nogu", "Oolah", "Ootah",
                                    "Ovak", "Ownka", "Puyet",
                                    "Reeza", "Shautha", "Silgre",
                                    "Sutha", "Tagga", "Tawar",
                                    "Tomph", "Ubada", "Vanchu",
                                    "Vola", "Volen", "Vorka",
                                    "Yevelda", "Zagga"]
            elif gender in ["male"]:
                self.first_names = ["Argran", "Braak", "Brug",
                                    "Cagak", "Dench", "Dorn",
                                    "Dren", "Druuk", "Feng",
                                    "Gell", "Gnarsh", "Grumbar",
                                    "Gubrash", "Hagren", "Henk",
                                    "Hogar", "Holg", "Imsh",
                                    "Karash", "Karg", "Keth",
                                    "Korag", "Krusk", "Lubash",
                                    "Megged", "Mhurren", "Mord",
                                    "Morg", "Nil", "Nybarg",
                                    "Odorr", "Ohr", "Rendar",
                                    "Resh", "Ront", "Rrath",
                                    "Sark", "Scrag", "Sheggen",
                                    "Shump", "Tanglar", "Tarak",
                                    "Thar", "Thokk", "Trag",
                                    "Ugarth", "Varg", "Vilberg",
                                    "Yurk", "Zed"]
            else:
                self.first_names = ["Piggu", "Parod", "Buordud",
                                    "Lorzub", "Crothu", "Urag",
                                    "Xurug", "Xuk", "Pretkag",
                                    "Turge", "Sumhug", "Sugha",
                                    "Curbag", "Kegth", "Wumkbanok",
                                    "Gholug", "Opilge", "Vurbag",
                                    "Ug", "Mudagog", "Sugbu",
                                    "Welub", "Vlorg", "Mash",
                                    "Seakgu", "Tilge", "Tagdud",
                                    "Holkurg", "Yahigig", "Jogug",
                                    "Borug", "Pregu", "Gulrn",
                                    "Guag", "Vabugbu", "Xagu",
                                    "Nargulg", "Vagungad", "Nugbu",
                                    "Yakha", "Fargigoth", "Karrhig",
                                    "Yagnar", "Bat", "Umhra",
                                    "Yerug", "Sargulg", "Pofhug",
                                    "Valthurg", "Jorgagu"]
        elif race in ["feral tiefling", "infernal tiefling"]:
            if gender in ["female"]:
                self.first_names = ["Akta", "Anakis", "Armara",
                                    "Astaro", "Aym", "Azza",
                                    "Beleth", "Bryseis", "Bune",
                                    "Criella", "Damaia", "Decarabia",
                                    "Ea", "Gadreel", "Gomory",
                                    "Hecat", "Ishte", "Jezebeth",
                                    "Kali", "Kallista", "Kasdeya",
                                    "Lerissa", "Lilith", "Makaria",
                                    "Manea", "Markosian", "Mastema"
                                                          "Naamah", "Nemeia", "Nija",
                                    "Orianna", "Osah", "Phelaia",
                                    "Prosperine", "Purah", "Pyra",
                                    "Rieta", "Ronobe", "Ronwe",
                                    "Seddit", "Seere", "Sekhmet",
                                    "Semyaza", "Shava", "Shax",
                                    "Sorath", "Uzza", "Vapula",
                                    "Vepar", "Verin"]
            elif gender in ["male"]:
                self.first_names = ["Abad", "Ahrim", "Akmen",
                                    "Amnon", "Andram", "Astar",
                                    "Balam", "Barakas", "Bathin",
                                    "Caim", "Chem", "Cimer",
                                    "Cressel", "Damakos", "Ekemon",
                                    "Euron", "Fenriz", "Forcas",
                                    "Habor", "Iados", "Kairon",
                                    "Leucis", "Mamnen", "Mantus",
                                    "Marbas", "Melech", "Merihim",
                                    "Modean", "Mordai", "Mormo",
                                    "Morthos", "Nicor", "Nirgel",
                                    "Oriax", "Paymon", "Pelaios",
                                    "Purson", "Qemuel", "Raam",
                                    "Rimmon", "Sammal", "Skamos",
                                    "Tethren", "Thamuz", "Therai",
                                    "Valafar", "Vassago", "Xappan",
                                    "Zepar", "Zephan"]
            else:
                self.first_names = ["Akta", "Anakis", "Armara",
                                    "Astaro", "Aym", "Azza",
                                    "Beleth", "Bryseis", "Bune",
                                    "Criella", "Damaia", "Decarabia",
                                    "Ea", "Gadreel", "Gomory",
                                    "Hecat", "Ishte", "Jezebeth",
                                    "Kali", "Kallista", "Kasdeya",
                                    "Lerissa", "Lilith", "Makaria",
                                    "Manea", "Markosian", "Mastema"
                                                          "Naamah", "Nemeia", "Nija",
                                    "Orianna", "Osah", "Phelaia",
                                    "Prosperine", "Purah", "Pyra",
                                    "Rieta", "Ronobe", "Ronwe",
                                    "Seddit", "Seere", "Sekhmet",
                                    "Semyaza", "Shava", "Shax",
                                    "Sorath", "Uzza", "Vapula",
                                    "Vepar", "Verin", "Abad",
                                    "Ahrim", "Akmen", "Amnon",
                                    "Andram", "Astar", "Balam",
                                    "Barakas", "Bathin", "Caim",
                                    "Chem", "Cimer", "Cressel",
                                    "Damakos", "Ekemon", "Euron",
                                    "Fenriz", "Forcas", "Habor",
                                    "Iados", "Kairon", "Leucis",
                                    "Mamnen", "Mantus", "Marbas",
                                    "Melech", "Merihim", "Modean",
                                    "Mordai", "Mormo", "Morthos",
                                    "Nicor", "Nirgel", "Oriax",
                                    "Paymon", "Pelaios", "Purson",
                                    "Qemuel", "Raam", "Rimmon",
                                    "Sammal", "Skamos", "Tethren",
                                    "Thamuz", "Therai", "Valafar",
                                    "Vassago", "Xappan", "Zepar", "Zephan"]
        elif race in ["goliath"]:
            self.first_names = ["Aukan", "Eglath", "Gae - Al",
                                "Guathak", "Ilikan", "Keothi",
                                "Kuori", "Lo - Kang", "Manneo",
                                "Maveith", "Nalla", "Orilo",
                                "Paavu", "Pethani", "Thalai",
                                "Thotham", "Uthal", "Vaunea",
                                "Vimak", "Alexandrine", "Alyshialynn",
                                "Boudicca", "Farren", "Fautave",
                                "Sieglinde", "Amaury", "Barret",
                                "Fenyang", "Torrence", "Somerild",
                                "Sosthenes", "Marhak", "Tarakan",
                                "Thorein", "Kanavek", "Lazakan",
                                "Apakin", "Agnoth", "Maukein",
                                "Vegagath", "Kazazak", "Naragun",
                                "Kavarath", "Lororok", "Neodak",
                                "Vipath", "Khulig", "Pagath",
                                "Moroth", "Tharok"]
        elif race in ["kenku"]:
            self.first_names = ["Dribbler", "Coyote Yowl", "Tree Creak",
                                "Donkey Stomp", "Hyena Cackle", "Bear Step",
                                "Leather Smack", "Wood Crack", "Bowstring Stretch",
                                "Cutter", "Dino Growl", "Ape Hoot", "Dragon Bite",
                                "Chisel Cut", "Sail Slap", "Paint Drop",
                                "Spitter", "Dog Run", "Chirper",
                                "Squirrel Nibble", "Net Cast", "Cow Step",
                                "Rat Rustle", "Vulture Scream", "Wood Chop",
                                "Hammer Clank", "Brush Stroke", "Dragon Roar",
                                "Croaker", "Book Drop", "Singer",
                                "Biter", "Panda Sneeze", "Potion Splash",
                                "Rope Slap", "Leather Smack", "Beaver Call",
                                "Goat Chew", "Hatchet Chop", "Squeaker",
                                "Lute String", "Growler", "Shrieker",
                                "Mouse Squeak", "Duck Quacker", "Beaver Nibble",
                                "Barker", "Neigher", "Dragon Breath", "Warbler"]
        elif race in ["lizardfolk"]:
            self.first_names = ["Achuak", "Aryte", "Baeshra",
                                "Darastrix", "Garut", "Irthos",
                                "Jhank", "Kepesk", "Kethend",
                                "Korth", "Kosj", "Kothar",
                                "Litrix", "Mirik", "Othokent",
                                "Sauriv", "Throden", "Thurkear",
                                "Usk", "Valignat", "Vargach",
                                "Verthica", "Vutha", "Vyth",
                                "Ond", "Du", "Trilron",
                                "Thrillisj", "Mergork", "Sushru",
                                "Voshrird", "Mipiri", "Teskitaerth",
                                "Githitis", "Nor", "Trath",
                                "Thrutheash", "Shollint", "Jherty",
                                "Aurthath", "Tugry", "Vurkarru",
                                "Neghisro", "Ogusrirth", "Aat",
                                "Art", "Lishryk", "Ulrurk",
                                "Ogruch", "Dulro"]
        elif race in ["tabaxi"]:
            self.first_names = ["Cloud on the Mountaintop (Cloud)", "Five Timber (Timber)",
                                "Jade Shoe (Jade)", "Left-Handed Hummingbird (Hummingbird)",
                                "Seven Thundercloud (Thunder)", "Skirt of Snakes (Skirt)",
                                "Smoking Mirror (Smoke)", "Piece of the Puzzle (Piece)",
                                "Luck of the Draw (Luck)", "Tale of Wonder (Tale)",
                                "Art of Shadows (Art)", "Solstice of Summer (Solstice)",
                                "Quick Wing (Quick)", "Icy Cable (Icy)",
                                "Angelic Boot (Boot)", "Stout Flower (Flower)"
                                                       "Bright Chains (Chains)", "Dew on the Grass (Dew)",
                                "Veil of a Mask (Veil)", "Ink on Skin (Ink)",
                                "Daydream at Night (Dream)", "Blazing Fire (Blaze)",
                                "Dynamic Link (Dynamic)", "Flawless Wave (Wave)",
                                "Hidden Knot (Knot)", "Half River (Half)",
                                "Active Fang (Active)", "Ink on Skin (Ink)",
                                "Storm on the Horizon (Storm)", "Jewel of the Mountain (Jewel)",
                                "Flickering Fire (Fire)", "Snapping Branch (Snap)",
                                "Amused Frog (Amused)", "Bright Canvas (Bright)",
                                "Bold Wonder (Wonder)", "Jolly Ink (Ink)",
                                "Little Tale (Little)", "Ice in Summer (Ice)",
                                "Burden of Chains (Chains)", "Hot as Fire (Fire)",
                                "Stroke of a Brush (Brush)", "Fish in the River (River)",
                                "Lost Time (Time)", "Ruby Edge (Edge)",
                                "Radiant Shadow (Radiant)", "Quick Ice (Quick)",
                                "Six Mark (Mark)", "Stroke of a Brush (Brush)",
                                "Call of a Bird (Bird)", "Spark of Life (Spark)"]
        elif race in ["aarakocra"]:
            self.first_names = ["Arc", "Grouhk", "Rhas",
                                "Duss", "Ziss", "Creqeed",
                                "Kheqe", "Ouqeer", "Acis",
                                "Kluiellark", "Zus", "Grur",
                                "Crus", "Ig", "Dess", "Qhucic",
                                "Rhullehk", "Irerr", "Kheqi",
                                "Graqes", "Oof", "Eess",
                                "Qal", "Aiar", "Qha",
                                "Qreqic", "Ellir", "Dacciaf",
                                "Akic", "Krookkerr", "Riss",
                                "Qhuie", "Id", "Qhuc",
                                "Klirr", "Ricik", "Qlaccel",
                                "Qhoulif", "Khaccarr", "Zarrirrk",
                                "Kleck", "Aef", "Yua",
                                "Qhoor", "Kac", "Qluarrerrk",
                                "Ooci", "Clilihk", "Geliss", "Rookkirk"]
        elif race in ["air genasi"]:
            self.first_names = ["Breeze", "Wind", "Draft",
                                "Heaven", "Puff", "Breath",
                                "Gust", "Whiff", "Gasp",
                                "Gale", "Squall", "Sky",
                                "Azure", "Empyrean", "Flutter",
                                "Tempest", "Typhoon", "Zephyr", "Aero"]
        elif race in ["water genasi"]:
            self.first_names = ["Rain", "Drizzle", "Flood",
                                "River", "Stream", "Beck",
                                "Brook", "Creek", "Lake",
                                "Pond", "Surf", "Tide",
                                "Rapids", "Aquifer"]
        elif race in ["earth genasi"]:
            self.first_names = ["Dirt", "Clay", "Rock",
                                "Gravel", "Mud", "Sand",
                                "Land", "Terrain", "Ground",
                                "Soil", "Stone", "Shale"]
        elif race in ["fire genasi"]:
            self.first_names = ["Blaze", "Inferno", "Coal",
                                "Ember", "Flame", "Pyre",
                                "Tinder", "Ash", "Cinder",
                                "Kindling", "Flare"]
        elif race in ["hobgoblin", "goblin"]:
            if gender in ["female"]:
                self.first_names = ["Steth", "Flulm", "Thing",
                                    "Cuth", "Trehxa", "Vernirte",
                                    "Jemoifsai", "Liestrelea", "Rebarx",
                                    "Ursesh", "Klols", "Wroifsai",
                                    "Eegee", "Jynxea", "Alm",
                                    "Uvzialx", "Swyrrirt", "Chagkosx",
                                    "Ientals", "Topnuq", "Uifia",
                                    "Creexai", "Ex", "Qesx",
                                    "Trof", "Prohzaanx", "Qoreax",
                                    "Swoignax", "Qaknuzz", "Qiohdeese",
                                    "Joix", "Wriefz", "Phinx",
                                    "Qialke", "Wrox", "Uillaahx",
                                    "Bhamzialm", "Laamrinx", "Stuitlulx",
                                    "Raaggazi", "Blieh", "Ienia",
                                    "Gniogsia", "Oxi", "Phafs",
                                    "Asbazia", "Nitteah", "Wolbeenea",
                                    "Qitzeaxi", "Griavurx"]
            elif gender in ["male"]:
                self.first_names = ["Slic", "Clolb", "Pluik",
                                    "Iorm", "Pleeg", "Blibrozz",
                                    "Vrytliags", "Plaabrox", "Iotviarm",
                                    "Prezleabs", "Kraal", "Hesb",
                                    "Plit", "Isb", "Bliolx",
                                    "Groidvus", "Wraaklarm", "Zrearvix",
                                    "Britnakz", "Rutybs", "Gnuing",
                                    "Biorm", "Vriol", "Gring",
                                    "Frots", "Evzoirt", "Xekulb",
                                    "Wrasziegs", "Ugdisz", "Xisrioc",
                                    "Zriot", "Freng", "Zeang",
                                    "Ekx", "Xard", "Gnagtog",
                                    "Balil", "Draahdits", "Ebleert",
                                    "Vusdik", "Labs", "Furk",
                                    "Stas", "Viekx", "Alk",
                                    "Imil", "Brokkikz", "Cletzoink",
                                    "Covoq", "Frozit"]
            else:
                self.first_names = ["Steth", "Flulm", "Thing",
                                    "Cuth", "Trehxa", "Vernirte",
                                    "Jemoifsai", "Liestrelea", "Rebarx",
                                    "Ursesh", "Klols", "Wroifsai",
                                    "Eegee", "Jynxea", "Alm",
                                    "Uvzialx", "Swyrrirt", "Chagkosx",
                                    "Ientals", "Topnuq", "Uifia",
                                    "Creexai", "Ex", "Qesx", "Trof",
                                    "Prohzaanx", "Qoreax", "Swoignax",
                                    "Qaknuzz", "Qiohdeese", "Joix",
                                    "Wriefz", "Phinx", "Qialke",
                                    "Wrox", "Uillaahx", "Bhamzialm",
                                    "Laamrinx", "Stuitlulx", "Raaggazi",
                                    "Blieh", "Ienia", "Gniogsia",
                                    "Oxi", "Phafs", "Asbazia",
                                    "Nitteah", "Wolbeenea", "Qitzeaxi",
                                    "Griavurx", "Slic", "Clolb",
                                    "Pluik", "Iorm", "Pleeg",
                                    "Blibrozz", "Vrytliags", "Plaabrox",
                                    "Iotviarm", "Prezleabs", "Kraal",
                                    "Hesb", "Plit", "Isb",
                                    "Bliolx", "Groidvus", "Wraaklarm",
                                    "Zrearvix", "Britnakz", "Rutybs",
                                    "Gnuing", "Biorm", "Vriol",
                                    "Gring", "Frots", "Evzoirt",
                                    "Xekulb", "Wrasziegs", "Ugdisz",
                                    "Xisrioc", "Zriot", "Freng",
                                    "Zeang", "Ekx", "Xard",
                                    "Gnagtog", "Balil", "Draahdits",
                                    "Ebleert", "Vusdik", "Labs",
                                    "Furk", "Stas", "Viekx",
                                    "Alk", "Imil", "Brokkikz",
                                    "Cletzoink", "Covoq", "Frozit"]
        elif race in ["triton"]:
            if gender in ["female"]:
                self.first_names = ["Folyn", "Flamlyn", "Wotlyn",
                                    "Whashyn", "Ethlunyn", "Vlilahyn",
                                    "Bhoshamyn", "Usnelyn", "Udilyn",
                                    "Doslyn", "Yulthyn", "Yetyn",
                                    "Eslimyn", "Berlolyn", "Besluren",
                                    "Oddyn", "Onlyn", "Faddahyn",
                                    "Derimyn", "Letledyn", "Athlomyn",
                                    "Udyn", "Woryn", "Etyn",
                                    "Adamyn", "Aslyn", "Isedyn",
                                    "Mistemyn", "Atlelyn", "Esenyn",
                                    "Feddyn", "Lethlyn", "Athlalyn",
                                    "Bonryn", "Astyn", "Sosnehyn",
                                    "Shadyn", "Balyn", "Shunlyn",
                                    "Desteryn", "Hethlyn", "Flitryn",
                                    "Etlyn", "Madyn", "Oglyn",
                                    "Usyn", "Amlunyn", "Esnumyn",
                                    "Athryn", "Whedryn"]
            elif gender in ["male"]:
                self.first_names = ["Dimnis", "Veles", "Dharvas",
                                    "Canlas", "Nilmis", "Kilis",
                                    "Velmes", "Middis", "Maras",
                                    "Carvas", "Jildis", "Namras",
                                    "Zurus", "Velnes", "Dirzis",
                                    "Denves", "Rurlus", "Kahras",
                                    "Vimnis", "Mehres", "Zahnas",
                                    "Jornos", "Mernes", "Keves",
                                    "Regles", "Monlos", "Vomnos",
                                    "Denres", "Conos", "Reves",
                                    "Rivnis", "Zildis", "Rarnas",
                                    "Cemres", "Norzos", "Zavas",
                                    "Ronos", "Kaglas", "Nilis",
                                    "Jolmos", "Cinvis", "Korzos",
                                    "Kinnis", "Vulus", "Celmes",
                                    "Ciris", "Karzas", "Civnis",
                                    "Marlas", "Davnas"]
            else:
                self.first_names = ["Folyn", "Flamlyn", "Wotlyn",
                                    "Whashyn", "Ethlunyn", "Vlilahyn",
                                    "Bhoshamyn", "Usnelyn", "Udilyn",
                                    "Doslyn", "Yulthyn", "Yetyn",
                                    "Eslimyn", "Berlolyn", "Besluren",
                                    "Oddyn", "Onlyn", "Faddahyn",
                                    "Derimyn", "Letledyn", "Athlomyn",
                                    "Udyn", "Woryn", "Etyn",
                                    "Adamyn", "Aslyn", "Isedyn",
                                    "Mistemyn", "Atlelyn", "Esenyn",
                                    "Feddyn", "Lethlyn", "Athlalyn",
                                    "Bonryn", "Astyn", "Sosnehyn",
                                    "Shadyn", "Balyn", "Shunlyn",
                                    "Desteryn", "Hethlyn", "Flitryn",
                                    "Etlyn", "Madyn", "Oglyn",
                                    "Usyn", "Amlunyn", "Esnumyn",
                                    "Athryn", "Whedryn", "Dimnis",
                                    "Veles", "Dharvas", "Canlas",
                                    "Nilmis", "Kilis", "Velmes",
                                    "Middis", "Maras", "Carvas",
                                    "Jildis", "Namras", "Zurus",
                                    "Velnes", "Dirzis", "Denves",
                                    "Rurlus", "Kahras", "Vimnis",
                                    "Mehres", "Zahnas", "Jornos",
                                    "Mernes", "Keves", "Regles",
                                    "Monlos", "Vomnos", "Denres",
                                    "Conos", "Reves", "Rivnis",
                                    "Zildis", "Rarnas", "Cemres",
                                    "Norzos", "Zavas", "Ronos",
                                    "Kaglas", "Nilis", "Jolmos",
                                    "Cinvis", "Korzos", "Kinnis",
                                    "Vulus", "Celmes", "Ciris",
                                    "Karzas", "Civnis", "Marlas", "Davnas"]
        elif race in ["kobold"]:
            self.first_names = ["Gen", "Snax", "Ruks",
                                "Zis", "Maple",
                                "Noldi", "Zeplu", "Gabi",
                                "Ovna", "Rato", "Sud",
                                "Kus", "Snav", "Doss",
                                "Vaggi", "Delbi", "Are",
                                "Mehso", "Nivu", "Okle",
                                "Men", "Tarn", "Son",
                                "Rurn", "Nurko", "Kagne",
                                "Rarte", "Tappi", "Adra",
                                "Snohle", "Zav", "Snad",
                                "Zam", "Gess", "Volti",
                                "Hutro", "Ulte", "Ilgo",
                                "Iru", "Ikdi", "Kun",
                                "Nott", "Nor", "Zos",
                                "Zoku", "Migli", "Zehli",
                                "Nodre", "Elle", "Dihsi"]
        else:
            # self.first_names = ["other"]
            self.human_names = HumanNames(skin_color, gender)
            self.first_names = self.human_names.generate_name()
        self.generate_name()

    def generate_name(self):
        first_name = random.choice(self.first_names)
        return first_name
